[general]
# Updated configuration for production deployment
dataFrameSerialization = "legacy"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

# Deployment timestamp: 2025-10-06 14:55:42
